<?php

$routes += [
	"/music" => __MODULES__ . "/music/routes/index.php",
	"/music/add-songs" => __MODULES__ . "/music/routes/addSongs.php",
	"/music/songs" => __MODULES__ . "/music/routes/songs.php",
	"/music/artists" => __MODULES__ . "/music/routes/artists.php",
	"/music/albums" => __MODULES__ . "/music/routes/albums.php",
	"/music/audit" => __MODULES__ . "/music/routes/audit.php",
	"/music/register" => __MODULES__ . "/music/routes/register.php",
	"/music/login" => __MODULES__ . "/music/routes/login.php",
	"/music/logout" => __MODULES__ . "/music/routes/logout.php",
	"/music/language" => __MODULES__ . "/music/routes/language.php",
	"/music/colour" => __MODULES__ . "/music/routes/colour.php",
	"/music/invites" => __MODULES__ . "/music/routes/invites.php",
	"/music/accounts" => __MODULES__ . "/music/routes/accounts.php",
	"/music/ajax/artist-alias" => __MODULES__ . "/music/ajax/artistAlias.php",
	"/music/ajax/song" => __MODULES__ . "/music/ajax/song.php",
	"/music/ajax/song-edit" => __MODULES__ . "/music/ajax/songEdit.php",
	"/music/ajax/song-rating" => __MODULES__ . "/music/ajax/songRating.php",
	"/music/ajax/song-rating-poll" => __MODULES__ . "/music/ajax/songRatingPoll.php",
	"/music/ajax/album" => __MODULES__ . "/music/ajax/album.php",
	"/music/ajax/album-card" => __MODULES__ . "/music/ajax/albumCard.php",
	"/music/ajax/album-options" => __MODULES__ . "/music/ajax/albumOptions.php",
	"/music/ajax/album-edit" => __MODULES__ . "/music/ajax/albumEdit.php",
	"/music/ajax/album-track" => __MODULES__ . "/music/ajax/albumTrack.php",
	"/music/ajax/song-artist" => __MODULES__ . "/music/ajax/songArtist.php",
	"/music/ajax/song-album" => __MODULES__ . "/music/ajax/songAlbum.php",
	"/music/ajax/song-link" => __MODULES__ . "/music/ajax/songLink.php",
	"/music/ajax/song-year" => __MODULES__ . "/music/ajax/songYear.php",
	"/music/ajax/song-duration" => __MODULES__ . "/music/ajax/songDuration.php",
];
